//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://services.hilton.com/types/", ClrNamespace="services.hilton.com.types")]

namespace services.hilton.com.types
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomReservation", Namespace="http://services.hilton.com/types/")]
    public partial class RoomReservation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string guestNameField;
        
        private int roomNumberField;
        
        private System.Nullable<System.DateTime> checkoutField;
        
        private string hotelField;
        
        private System.Nullable<System.DateTime> checkinField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string guestName
        {
            get
            {
                return this.guestNameField;
            }
            set
            {
                this.guestNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int roomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> checkout
        {
            get
            {
                return this.checkoutField;
            }
            set
            {
                this.checkoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string hotel
        {
            get
            {
                return this.hotelField;
            }
            set
            {
                this.hotelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> checkin
        {
            get
            {
                return this.checkinField;
            }
            set
            {
                this.checkinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://services.hilton.com/types/")]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeErrorField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string codeError
        {
            get
            {
                return this.codeErrorField;
            }
            set
            {
                this.codeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public static implicit operator Status(global::Status v)
        {
            throw new NotImplementedException();
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://services.hilton.com/", ConfigurationName="HiltonBookingService")]
public interface HiltonBookingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://services.hilton.com//bookRoom", ReplyAction="*")]
    bookRoomResponse bookRoom(bookRoomRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://services.hilton.com//bookRoom", ReplyAction="*")]
    System.Threading.Tasks.Task<bookRoomResponse> bookRoomAsync(bookRoomRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://services.hilton.com//cancelBooking", ReplyAction="*")]
    cancelBookingResponse cancelBooking(cancelBookingRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://services.hilton.com//cancelBooking", ReplyAction="*")]
    System.Threading.Tasks.Task<cancelBookingResponse> cancelBookingAsync(cancelBookingRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class bookRoomRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="bookRoomElementRequest", Namespace="http://services.hilton.com/types/", Order=0)]
    public bookRoomRequestBody Body;
    
    public bookRoomRequest()
    {
    }
    
    public bookRoomRequest(bookRoomRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.hilton.com/types/")]
public partial class bookRoomRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public services.hilton.com.types.RoomReservation RoomReservation;
    
    public bookRoomRequestBody()
    {
    }
    
    public bookRoomRequestBody(services.hilton.com.types.RoomReservation RoomReservation)
    {
        this.RoomReservation = RoomReservation;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class bookRoomResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="bookRoomElementResponse", Namespace="http://services.hilton.com/types/", Order=0)]
    public bookRoomResponseBody Body;
    
    public bookRoomResponse()
    {
    }
    
    public bookRoomResponse(bookRoomResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.hilton.com/types/")]
public partial class bookRoomResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public bool result;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string bookingId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public services.hilton.com.types.Status Status;
    
    public bookRoomResponseBody()
    {
    }
    
    public bookRoomResponseBody(bool result, string bookingId, services.hilton.com.types.Status Status)
    {
        this.result = result;
        this.bookingId = bookingId;
        this.Status = Status;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class cancelBookingRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelbookingRequest", Namespace="http://services.hilton.com/types/", Order=0)]
    public cancelBookingRequestBody Body;
    
    public cancelBookingRequest()
    {
    }
    
    public cancelBookingRequest(cancelBookingRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.hilton.com/types/")]
public partial class cancelBookingRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string bookingId;
    
    public cancelBookingRequestBody()
    {
    }
    
    public cancelBookingRequestBody(string bookingId)
    {
        this.bookingId = bookingId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class cancelBookingResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelbookingResponse", Namespace="http://services.hilton.com/types/", Order=0)]
    public cancelBookingResponseBody Body;
    
    public cancelBookingResponse()
    {
    }
    
    public cancelBookingResponse(cancelBookingResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.hilton.com/types/")]
public partial class cancelBookingResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public bool result;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string cancelId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public services.hilton.com.types.Status Status;
    
    public cancelBookingResponseBody()
    {
    }
    
    public cancelBookingResponseBody(bool result, string cancelId, services.hilton.com.types.Status Status)
    {
        this.result = result;
        this.cancelId = cancelId;
        this.Status = Status;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface HiltonBookingServiceChannel : HiltonBookingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HiltonBookingServiceClient : System.ServiceModel.ClientBase<HiltonBookingService>, HiltonBookingService
{
    
    public HiltonBookingServiceClient()
    {
    }
    
    public HiltonBookingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HiltonBookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HiltonBookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HiltonBookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bookRoomResponse HiltonBookingService.bookRoom(bookRoomRequest request)
    {
        return base.Channel.bookRoom(request);
    }
    
    public bool bookRoom(services.hilton.com.types.RoomReservation RoomReservation, out string bookingId, out services.hilton.com.types.Status Status)
    {
        bookRoomRequest inValue = new bookRoomRequest();
        inValue.Body = new bookRoomRequestBody();
        inValue.Body.RoomReservation = RoomReservation;
        bookRoomResponse retVal = ((HiltonBookingService)(this)).bookRoom(inValue);
        bookingId = retVal.Body.bookingId;
        Status = retVal.Body.Status;
        return retVal.Body.result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<bookRoomResponse> HiltonBookingService.bookRoomAsync(bookRoomRequest request)
    {
        return base.Channel.bookRoomAsync(request);
    }
    
    public System.Threading.Tasks.Task<bookRoomResponse> bookRoomAsync(services.hilton.com.types.RoomReservation RoomReservation)
    {
        bookRoomRequest inValue = new bookRoomRequest();
        inValue.Body = new bookRoomRequestBody();
        inValue.Body.RoomReservation = RoomReservation;
        return ((HiltonBookingService)(this)).bookRoomAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    cancelBookingResponse HiltonBookingService.cancelBooking(cancelBookingRequest request)
    {
        return base.Channel.cancelBooking(request);
    }
    
    public bool cancelBooking(string bookingId, out string cancelId, out services.hilton.com.types.Status Status)
    {
        cancelBookingRequest inValue = new cancelBookingRequest();
        inValue.Body = new cancelBookingRequestBody();
        inValue.Body.bookingId = bookingId;
        cancelBookingResponse retVal = ((HiltonBookingService)(this)).cancelBooking(inValue);
        cancelId = retVal.Body.cancelId;
        Status = retVal.Body.Status;
        return retVal.Body.result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<cancelBookingResponse> HiltonBookingService.cancelBookingAsync(cancelBookingRequest request)
    {
        return base.Channel.cancelBookingAsync(request);
    }
    
    public System.Threading.Tasks.Task<cancelBookingResponse> cancelBookingAsync(string bookingId)
    {
        cancelBookingRequest inValue = new cancelBookingRequest();
        inValue.Body = new cancelBookingRequestBody();
        inValue.Body.bookingId = bookingId;
        return ((HiltonBookingService)(this)).cancelBookingAsync(inValue);
    }
}
