//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService", ConfigurationName = "HiltonRoomService")]
public interface HiltonRoomService
{

    // CODEGEN: Generating message contract since the operation initiate is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.oracle.com/HiltonRoomService/initiate", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    initiateResponse initiate(initiateRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.oracle.com/HiltonRoomService/initiate", ReplyAction = "*")]
    System.Threading.Tasks.Task<initiateResponse> initiateAsync(initiateRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.oracle.com/HiltonRoomService")]
public partial class HiltonRoomServiceProcessRequest
{

    private string cityField;

    private string countryField;

    private System.DateTime checkInField;

    private System.DateTime checkOutField;

    private int roomsField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Check-In", DataType = "date", Order = 2)]
    public System.DateTime CheckIn
    {
        get
        {
            return this.checkInField;
        }
        set
        {
            this.checkInField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Check-Out", DataType = "date", Order = 3)]
    public System.DateTime CheckOut
    {
        get
        {
            return this.checkOutField;
        }
        set
        {
            this.checkOutField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "int", Order = 4)]
    public int Rooms
    {
        get
        {
            return this.roomsField;
        }
        set
        {
            this.roomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService")]
public partial class Room
{

    private int numberField;

    private float priceField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "int", Order = 0)]
    public int Number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public float Price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService")]
public partial class Hotel
{

    private string nameField;

    private string addressField;

    private string cityField;

    private string countryField;

    private Room[] roomsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rooms", Order = 4)]
    public Room[] Rooms
    {
        get
        {
            return this.roomsField;
        }
        set
        {
            this.roomsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService")]
public partial class Status
{

    private string codeField;

    private string errorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.oracle.com/HiltonRoomService")]
public partial class HiltonRoomServiceProcessResponse
{

    private Status statusField;

    private Hotel[] resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Hotels", IsNullable = false)]
    public Hotel[] result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class initiateRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService", Order = 0)]
    public HiltonRoomServiceProcessRequest HiltonRoomServiceProcessRequest;

    public initiateRequest()
    {
    }

    public initiateRequest(HiltonRoomServiceProcessRequest HiltonRoomServiceProcessRequest)
    {
        this.HiltonRoomServiceProcessRequest = HiltonRoomServiceProcessRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class initiateResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.oracle.com/HiltonRoomService", Order = 0)]
    public HiltonRoomServiceProcessResponse HiltonRoomServiceProcessResponse;

    public initiateResponse()
    {
    }

    public initiateResponse(HiltonRoomServiceProcessResponse HiltonRoomServiceProcessResponse)
    {
        this.HiltonRoomServiceProcessResponse = HiltonRoomServiceProcessResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface HiltonRoomServiceChannel : HiltonRoomService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HiltonRoomServiceClient : System.ServiceModel.ClientBase<HiltonRoomService>, HiltonRoomService
{

    public HiltonRoomServiceClient()
    {
    }

    public HiltonRoomServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public HiltonRoomServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public HiltonRoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public HiltonRoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    initiateResponse HiltonRoomService.initiate(initiateRequest request)
    {
        return base.Channel.initiate(request);
    }

    public HiltonRoomServiceProcessResponse initiate(HiltonRoomServiceProcessRequest HiltonRoomServiceProcessRequest)
    {
        initiateRequest inValue = new initiateRequest();
        inValue.HiltonRoomServiceProcessRequest = HiltonRoomServiceProcessRequest;
        initiateResponse retVal = ((HiltonRoomService)(this)).initiate(inValue);
        return retVal.HiltonRoomServiceProcessResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<initiateResponse> HiltonRoomService.initiateAsync(initiateRequest request)
    {
        return base.Channel.initiateAsync(request);
    }

    public System.Threading.Tasks.Task<initiateResponse> initiateAsync(HiltonRoomServiceProcessRequest HiltonRoomServiceProcessRequest)
    {
        initiateRequest inValue = new initiateRequest();
        inValue.HiltonRoomServiceProcessRequest = HiltonRoomServiceProcessRequest;
        return ((HiltonRoomService)(this)).initiateAsync(inValue);
    }
}
