//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", ConfigurationName = "OrderService")]
public interface OrderService
{

    // CODEGEN: Generating message contract since the operation GetOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/GetOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetOrderResponse1 GetOrder(GetOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/GetOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetOrderResponse1> GetOrderAsync(GetOrderRequest1 request);

    // CODEGEN: Generating message contract since the operation PostOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PostOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PostOrderResponse1 PostOrder(PostOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PostOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<PostOrderResponse1> PostOrderAsync(PostOrderRequest1 request);

    // CODEGEN: Generating message contract since the operation PutOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PutOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PutOrderResponse1 PutOrder(PutOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PutOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<PutOrderResponse1> PutOrderAsync(PutOrderRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrderRequest
{

    private GetOrder orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public GetOrder Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrder
{

    private string orderCodeField;

    private System.DateTime orderDateField;

    //private bool orderDateFieldSpecified;

    private string orderStatusField;

    private decimal orderValueField;

    //private bool orderValueFieldSpecified;

    private string idTypeField;

    private string idNumberField;

    private string eventCodeField;

    private string hotelCodeField;

    private string transportCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
    public System.DateTime OrderDate
    {
        get
        {
            return this.orderDateField;
        }
        set
        {
            this.orderDateField = value;
        }
    }

    /// <remarks/>
    //[System.Xml.Serialization.XmlIgnoreAttribute()]
    //public bool OrderDateSpecified
    //{
    //    get
    //    {
    //        return this.orderDateFieldSpecified;
    //    }
    //    set
    //    {
    //        this.orderDateFieldSpecified = value;
    //    }
    //}

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }

    /// <remarks/>
    //[System.Xml.Serialization.XmlIgnoreAttribute()]
    //public bool OrderValueSpecified
    //{
    //    get
    //    {
    //        return this.orderValueFieldSpecified;
    //    }
    //    set
    //    {
    //        this.orderValueFieldSpecified = value;
    //    }
    //}

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string HotelCode
    {
        get
        {
            return this.hotelCodeField;
        }
        set
        {
            this.hotelCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string TransportCode
    {
        get
        {
            return this.transportCodeField;
        }
        set
        {
            this.transportCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class CancelOrder
{

    private string idTypeField;

    private string idNumberField;

    private string orderCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class RegOrder
{

    private string idTypeField;

    private string idNumberField;

    private string orderCodeField;

    private System.DateTime orderDateField;

    private string orderStatusField;

    private decimal orderValueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 3)]
    public System.DateTime OrderDate
    {
        get
        {
            return this.orderDateField;
        }
        set
        {
            this.orderDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class Order
{

    private string idTypeField;

    private string idNumberField;

    private string eventCodeField;

    private string hotelCodeField;

    private string transportCodeField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string HotelCode
    {
        get
        {
            return this.hotelCodeField;
        }
        set
        {
            this.hotelCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string TransportCode
    {
        get
        {
            return this.transportCodeField;
        }
        set
        {
            this.transportCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class OrderInfo
{

    private string orderCodeField;

    private System.DateTime orderDateField;

    private string orderStatusField;

    private decimal orderValueField;

    private string idTypeField;

    private string idNumberField;

    private string eventCodeField;

    private string hotelCodeField;

    private string transportCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
    public System.DateTime OrderDate
    {
        get
        {
            return this.orderDateField;
        }
        set
        {
            this.orderDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string HotelCode
    {
        get
        {
            return this.hotelCodeField;
        }
        set
        {
            this.hotelCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string TransportCode
    {
        get
        {
            return this.transportCodeField;
        }
        set
        {
            this.transportCodeField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.touresbalon.com/OrderService")]
//public partial class Status
//{

//    private string codeRespField;

//    private string messageRespField;

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
//    public string CodeResp
//    {
//        get
//        {
//            return this.codeRespField;
//        }
//        set
//        {
//            this.codeRespField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
//    public string MessageResp
//    {
//        get
//        {
//            return this.messageRespField;
//        }
//        set
//        {
//            this.messageRespField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrderResponse
{

    private Status statusField;

    private OrderInfo[] resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Order", IsNullable = false)]
    public OrderInfo[] result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public GetOrderRequest GetOrderRequest;

    public GetOrderRequest1()
    {
    }

    public GetOrderRequest1(GetOrderRequest GetOrderRequest)
    {
        this.GetOrderRequest = GetOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public GetOrderResponse GetOrderResponse;

    public GetOrderResponse1()
    {
    }

    public GetOrderResponse1(GetOrderResponse GetOrderResponse)
    {
        this.GetOrderResponse = GetOrderResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PostOrderRequest
{

    private Order orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Order Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PostOrderResponse
{

    private Status statusField;

    private RegOrder resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public RegOrder result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PostOrderRequest PostOrderRequest;

    public PostOrderRequest1()
    {
    }

    public PostOrderRequest1(PostOrderRequest PostOrderRequest)
    {
        this.PostOrderRequest = PostOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PostOrderResponse PostOrderResponse;

    public PostOrderResponse1()
    {
    }

    public PostOrderResponse1(PostOrderResponse PostOrderResponse)
    {
        this.PostOrderResponse = PostOrderResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PutOrderRequest
{

    private CancelOrder orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public CancelOrder Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PutOrderResponse
{

    private Status statusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PutOrderRequest PutOrderRequest;

    public PutOrderRequest1()
    {
    }

    public PutOrderRequest1(PutOrderRequest PutOrderRequest)
    {
        this.PutOrderRequest = PutOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PutOrderResponse PutOrderResponse;

    public PutOrderResponse1()
    {
    }

    public PutOrderResponse1(PutOrderResponse PutOrderResponse)
    {
        this.PutOrderResponse = PutOrderResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface OrderServiceChannel : OrderService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OrderServiceClient : System.ServiceModel.ClientBase<OrderService>, OrderService
{

    public OrderServiceClient()
    {
    }

    public OrderServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public OrderServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetOrderResponse1 OrderService.GetOrder(GetOrderRequest1 request)
    {
        return base.Channel.GetOrder(request);
    }

    public GetOrderResponse GetOrder(GetOrderRequest GetOrderRequest)
    {
        GetOrderRequest1 inValue = new GetOrderRequest1();
        inValue.GetOrderRequest = GetOrderRequest;
        GetOrderResponse1 retVal = ((OrderService)(this)).GetOrder(inValue);
        return retVal.GetOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetOrderResponse1> OrderService.GetOrderAsync(GetOrderRequest1 request)
    {
        return base.Channel.GetOrderAsync(request);
    }

    public System.Threading.Tasks.Task<GetOrderResponse1> GetOrderAsync(GetOrderRequest GetOrderRequest)
    {
        GetOrderRequest1 inValue = new GetOrderRequest1();
        inValue.GetOrderRequest = GetOrderRequest;
        return ((OrderService)(this)).GetOrderAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PostOrderResponse1 OrderService.PostOrder(PostOrderRequest1 request)
    {
        return base.Channel.PostOrder(request);
    }

    public PostOrderResponse PostOrder(PostOrderRequest PostOrderRequest)
    {
        PostOrderRequest1 inValue = new PostOrderRequest1();
        inValue.PostOrderRequest = PostOrderRequest;
        PostOrderResponse1 retVal = ((OrderService)(this)).PostOrder(inValue);
        return retVal.PostOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PostOrderResponse1> OrderService.PostOrderAsync(PostOrderRequest1 request)
    {
        return base.Channel.PostOrderAsync(request);
    }

    public System.Threading.Tasks.Task<PostOrderResponse1> PostOrderAsync(PostOrderRequest PostOrderRequest)
    {
        PostOrderRequest1 inValue = new PostOrderRequest1();
        inValue.PostOrderRequest = PostOrderRequest;
        return ((OrderService)(this)).PostOrderAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PutOrderResponse1 OrderService.PutOrder(PutOrderRequest1 request)
    {
        return base.Channel.PutOrder(request);
    }

    public PutOrderResponse PutOrder(PutOrderRequest PutOrderRequest)
    {
        PutOrderRequest1 inValue = new PutOrderRequest1();
        inValue.PutOrderRequest = PutOrderRequest;
        PutOrderResponse1 retVal = ((OrderService)(this)).PutOrder(inValue);
        return retVal.PutOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PutOrderResponse1> OrderService.PutOrderAsync(PutOrderRequest1 request)
    {
        return base.Channel.PutOrderAsync(request);
    }

    public System.Threading.Tasks.Task<PutOrderResponse1> PutOrderAsync(PutOrderRequest PutOrderRequest)
    {
        PutOrderRequest1 inValue = new PutOrderRequest1();
        inValue.PutOrderRequest = PutOrderRequest;
        return ((OrderService)(this)).PutOrderAsync(inValue);
    }
}
