//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", ConfigurationName = "OrderService")]
public interface OrderService
{

    // CODEGEN: Generating message contract since the operation GetOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/GetOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetOrderResponse1 GetOrder(GetOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/GetOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetOrderResponse1> GetOrderAsync(GetOrderRequest1 request);

    // CODEGEN: Generating message contract since the operation PostOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PostOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PostOrderResponse1 PostOrder(PostOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PostOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<PostOrderResponse1> PostOrderAsync(PostOrderRequest1 request);

    // CODEGEN: Generating message contract since the operation PutOrder is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PutOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PutOrderResponse1 PutOrder(PutOrderRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/OrderService/PutOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<PutOrderResponse1> PutOrderAsync(PutOrderRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrderRequest
{

    private GetOrder orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public GetOrder Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrder
{

    private string orderCodeField;

    private System.DateTime orderDateStartField;

    private bool orderDateStartFieldSpecified;

    private System.DateTime orderDateEndField;

    private bool orderDateEndFieldSpecified;

    private string orderStatusField;

    private decimal orderValueField;

    private bool orderValueFieldSpecified;

    private long idUserField;

    private bool idUserFieldSpecified;

    private string idTypeField;

    private long idNumberField;

    private bool idNumberFieldSpecified;

    private string eventCodeField;

    private string hotelCodeField;

    private string hotelCompanyNameField;

    private string transportCodeField;

    private string transportCompanyNameField;

    private bool flagDetailField;

    private bool flagDetailFieldSpecified;

    private string typeQueryField;

    private long pageField;

    private bool pageFieldSpecified;

    private long regsPerPageField;

    private bool regsPerPageFieldSpecified;

    private long totalsRegsField;

    private bool totalsRegsFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
    public System.DateTime OrderDateStart
    {
        get
        {
            return this.orderDateStartField;
        }
        set
        {
            this.orderDateStartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderDateStartSpecified
    {
        get
        {
            return this.orderDateStartFieldSpecified;
        }
        set
        {
            this.orderDateStartFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 2)]
    public System.DateTime OrderDateEnd
    {
        get
        {
            return this.orderDateEndField;
        }
        set
        {
            this.orderDateEndField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderDateEndSpecified
    {
        get
        {
            return this.orderDateEndFieldSpecified;
        }
        set
        {
            this.orderDateEndFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderValueSpecified
    {
        get
        {
            return this.orderValueFieldSpecified;
        }
        set
        {
            this.orderValueFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public long IdUser
    {
        get
        {
            return this.idUserField;
        }
        set
        {
            this.idUserField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdUserSpecified
    {
        get
        {
            return this.idUserFieldSpecified;
        }
        set
        {
            this.idUserFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public long IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdNumberSpecified
    {
        get
        {
            return this.idNumberFieldSpecified;
        }
        set
        {
            this.idNumberFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 8)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 9)]
    public string HotelCode
    {
        get
        {
            return this.hotelCodeField;
        }
        set
        {
            this.hotelCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string HotelCompanyName
    {
        get
        {
            return this.hotelCompanyNameField;
        }
        set
        {
            this.hotelCompanyNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 11)]
    public string TransportCode
    {
        get
        {
            return this.transportCodeField;
        }
        set
        {
            this.transportCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
    public string TransportCompanyName
    {
        get
        {
            return this.transportCompanyNameField;
        }
        set
        {
            this.transportCompanyNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
    public bool FlagDetail
    {
        get
        {
            return this.flagDetailField;
        }
        set
        {
            this.flagDetailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FlagDetailSpecified
    {
        get
        {
            return this.flagDetailFieldSpecified;
        }
        set
        {
            this.flagDetailFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
    public string TypeQuery
    {
        get
        {
            return this.typeQueryField;
        }
        set
        {
            this.typeQueryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
    public long Page
    {
        get
        {
            return this.pageField;
        }
        set
        {
            this.pageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PageSpecified
    {
        get
        {
            return this.pageFieldSpecified;
        }
        set
        {
            this.pageFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
    public long RegsPerPage
    {
        get
        {
            return this.regsPerPageField;
        }
        set
        {
            this.regsPerPageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RegsPerPageSpecified
    {
        get
        {
            return this.regsPerPageFieldSpecified;
        }
        set
        {
            this.regsPerPageFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
    public long TotalsRegs
    {
        get
        {
            return this.totalsRegsField;
        }
        set
        {
            this.totalsRegsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalsRegsSpecified
    {
        get
        {
            return this.totalsRegsFieldSpecified;
        }
        set
        {
            this.totalsRegsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class CancelOrder
{

    private long idUserField;

    private string orderCodeField;

    private string statusField;

    private string hotelBookingIdField;

    private string hotelCancelIdField;

    private string transportBookingIdField;

    private string transportCancelIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public long IdUser
    {
        get
        {
            return this.idUserField;
        }
        set
        {
            this.idUserField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string HotelBookingId
    {
        get
        {
            return this.hotelBookingIdField;
        }
        set
        {
            this.hotelBookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string HotelCancelId
    {
        get
        {
            return this.hotelCancelIdField;
        }
        set
        {
            this.hotelCancelIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string TransportBookingId
    {
        get
        {
            return this.transportBookingIdField;
        }
        set
        {
            this.transportBookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string TransportCancelId
    {
        get
        {
            return this.transportCancelIdField;
        }
        set
        {
            this.transportCancelIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class RegOrder
{

    private string orderCodeField;

    private System.DateTime orderDateField;

    private string orderStatusField;

    private decimal orderValueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
    public System.DateTime OrderDate
    {
        get
        {
            return this.orderDateField;
        }
        set
        {
            this.orderDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class Transport
{

    private string bookingIdField;

    private string countryFromField;

    private string countryToField;

    private string cityFromField;

    private string cityToField;

    private string chairsField;

    private System.DateTime departureDepartDateField;

    private System.DateTime departureArrivingDateField;

    private System.DateTime returnDepartDateField;

    private System.DateTime returnArrivingDateField;

    private decimal valueField;

    private string companyNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string BookingId
    {
        get
        {
            return this.bookingIdField;
        }
        set
        {
            this.bookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string CountryFrom
    {
        get
        {
            return this.countryFromField;
        }
        set
        {
            this.countryFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CountryTo
    {
        get
        {
            return this.countryToField;
        }
        set
        {
            this.countryToField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string CityFrom
    {
        get
        {
            return this.cityFromField;
        }
        set
        {
            this.cityFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string CityTo
    {
        get
        {
            return this.cityToField;
        }
        set
        {
            this.cityToField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 5)]
    public string Chairs
    {
        get
        {
            return this.chairsField;
        }
        set
        {
            this.chairsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 6)]
    public System.DateTime DepartureDepartDate
    {
        get
        {
            return this.departureDepartDateField;
        }
        set
        {
            this.departureDepartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
    public System.DateTime DepartureArrivingDate
    {
        get
        {
            return this.departureArrivingDateField;
        }
        set
        {
            this.departureArrivingDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 8)]
    public System.DateTime ReturnDepartDate
    {
        get
        {
            return this.returnDepartDateField;
        }
        set
        {
            this.returnDepartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 9)]
    public System.DateTime ReturnArrivingDate
    {
        get
        {
            return this.returnArrivingDateField;
        }
        set
        {
            this.returnArrivingDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class Hotel
{

    private string bookingIdField;

    private string nameField;

    private string roomNumberField;

    private string addressField;

    private string countryField;

    private string cityField;

    private System.DateTime checkinField;

    private System.DateTime checkoutField;

    private string typeField;

    private decimal valueField;

    private string companyNameField;

    private string cantidadField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string BookingId
    {
        get
        {
            return this.bookingIdField;
        }
        set
        {
            this.bookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
    public string RoomNumber
    {
        get
        {
            return this.roomNumberField;
        }
        set
        {
            this.roomNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 6)]
    public System.DateTime Checkin
    {
        get
        {
            return this.checkinField;
        }
        set
        {
            this.checkinField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
    public System.DateTime Checkout
    {
        get
        {
            return this.checkoutField;
        }
        set
        {
            this.checkoutField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 11)]
    public string Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class Event
{

    private string eventCodeField;

    private string nameField;

    private string descriptionField;

    private System.DateTime dateField;

    private decimal valueField;

    private string cantidadField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 3)]
    public System.DateTime Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 5)]
    public string Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class Order
{

    private long idUserField;

    private Event eventField;

    private Hotel hotelField;

    private Transport transportField;

    private decimal totalValueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public long IdUser
    {
        get
        {
            return this.idUserField;
        }
        set
        {
            this.idUserField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public Event Event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public Hotel Hotel
    {
        get
        {
            return this.hotelField;
        }
        set
        {
            this.hotelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public Transport Transport
    {
        get
        {
            return this.transportField;
        }
        set
        {
            this.transportField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal TotalValue
    {
        get
        {
            return this.totalValueField;
        }
        set
        {
            this.totalValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetTransport
{

    private string bookingIdField;

    private string transportCodeField;

    private string countryFromField;

    private string countryToField;

    private string cityFromField;

    private string cityToField;

    private string chairsField;

    private System.DateTime departureDepartDateField;

    private System.DateTime departureArrivingDateField;

    private System.DateTime returnDepartDateField;

    private System.DateTime returnArrivingDateField;

    private decimal valueField;

    private string companyNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string BookingId
    {
        get
        {
            return this.bookingIdField;
        }
        set
        {
            this.bookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
    public string TransportCode
    {
        get
        {
            return this.transportCodeField;
        }
        set
        {
            this.transportCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CountryFrom
    {
        get
        {
            return this.countryFromField;
        }
        set
        {
            this.countryFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string CountryTo
    {
        get
        {
            return this.countryToField;
        }
        set
        {
            this.countryToField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string CityFrom
    {
        get
        {
            return this.cityFromField;
        }
        set
        {
            this.cityFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string CityTo
    {
        get
        {
            return this.cityToField;
        }
        set
        {
            this.cityToField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
    public string Chairs
    {
        get
        {
            return this.chairsField;
        }
        set
        {
            this.chairsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
    public System.DateTime DepartureDepartDate
    {
        get
        {
            return this.departureDepartDateField;
        }
        set
        {
            this.departureDepartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 8)]
    public System.DateTime DepartureArrivingDate
    {
        get
        {
            return this.departureArrivingDateField;
        }
        set
        {
            this.departureArrivingDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 9)]
    public System.DateTime ReturnDepartDate
    {
        get
        {
            return this.returnDepartDateField;
        }
        set
        {
            this.returnDepartDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 10)]
    public System.DateTime ReturnArrivingDate
    {
        get
        {
            return this.returnArrivingDateField;
        }
        set
        {
            this.returnArrivingDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetHotel
{

    private string bookingIdField;

    private string hotelCodeField;

    private string nameField;

    private string roomNumberField;

    private string addressField;

    private string countryField;

    private string cityField;

    private System.DateTime checkinField;

    private System.DateTime checkoutField;

    private string typeField;

    private decimal valueField;

    private string companyNameField;

    private string cantidadField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string BookingId
    {
        get
        {
            return this.bookingIdField;
        }
        set
        {
            this.bookingIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
    public string HotelCode
    {
        get
        {
            return this.hotelCodeField;
        }
        set
        {
            this.hotelCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string RoomNumber
    {
        get
        {
            return this.roomNumberField;
        }
        set
        {
            this.roomNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
    public System.DateTime Checkin
    {
        get
        {
            return this.checkinField;
        }
        set
        {
            this.checkinField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 8)]
    public System.DateTime Checkout
    {
        get
        {
            return this.checkoutField;
        }
        set
        {
            this.checkoutField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 12)]
    public string Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetEvent
{

    private string eventCodeField;

    private string nameField;

    private string descriptionField;

    private System.DateTime dateField;

    private decimal valueField;

    private string cantidadField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
    public string EventCode
    {
        get
        {
            return this.eventCodeField;
        }
        set
        {
            this.eventCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 3)]
    public System.DateTime Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 5)]
    public string Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class OrderInfo
{

    private string orderCodeField;

    private System.DateTime orderDateField;

    private string orderStatusField;

    private decimal orderValueField;

    private long idUserField;

    private string idTypeField;

    private long idNumberField;

    private GetEvent eventField;

    private GetHotel hotelField;

    private GetTransport transportField;

    private long totalsRegsField;

    private bool totalsRegsFieldSpecified;

    private decimal totalSoldField;

    private bool totalSoldFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string OrderCode
    {
        get
        {
            return this.orderCodeField;
        }
        set
        {
            this.orderCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 1)]
    public System.DateTime OrderDate
    {
        get
        {
            return this.orderDateField;
        }
        set
        {
            this.orderDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public decimal OrderValue
    {
        get
        {
            return this.orderValueField;
        }
        set
        {
            this.orderValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public long IdUser
    {
        get
        {
            return this.idUserField;
        }
        set
        {
            this.idUserField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public long IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public GetEvent Event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public GetHotel Hotel
    {
        get
        {
            return this.hotelField;
        }
        set
        {
            this.hotelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public GetTransport Transport
    {
        get
        {
            return this.transportField;
        }
        set
        {
            this.transportField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public long TotalsRegs
    {
        get
        {
            return this.totalsRegsField;
        }
        set
        {
            this.totalsRegsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalsRegsSpecified
    {
        get
        {
            return this.totalsRegsFieldSpecified;
        }
        set
        {
            this.totalsRegsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public decimal TotalSold
    {
        get
        {
            return this.totalSoldField;
        }
        set
        {
            this.totalSoldField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalSoldSpecified
    {
        get
        {
            return this.totalSoldFieldSpecified;
        }
        set
        {
            this.totalSoldFieldSpecified = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService")]
//public partial class Status
//{

//    private string codeRespField;

//    private string messageRespField;

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
//    public string CodeResp
//    {
//        get
//        {
//            return this.codeRespField;
//        }
//        set
//        {
//            this.codeRespField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
//    public string MessageResp
//    {
//        get
//        {
//            return this.messageRespField;
//        }
//        set
//        {
//            this.messageRespField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class GetOrderResponse
{

    private Status statusField;

    private OrderInfo[] resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Order", IsNullable = false)]
    public OrderInfo[] result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public GetOrderRequest GetOrderRequest;

    public GetOrderRequest1()
    {
    }

    public GetOrderRequest1(GetOrderRequest GetOrderRequest)
    {
        this.GetOrderRequest = GetOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public GetOrderResponse GetOrderResponse;

    public GetOrderResponse1()
    {
    }

    public GetOrderResponse1(GetOrderResponse GetOrderResponse)
    {
        this.GetOrderResponse = GetOrderResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PostOrderRequest
{

    private Order orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Order Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PostOrderResponse
{

    private Status statusField;

    private RegOrder resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public RegOrder result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PostOrderRequest PostOrderRequest;

    public PostOrderRequest1()
    {
    }

    public PostOrderRequest1(PostOrderRequest PostOrderRequest)
    {
        this.PostOrderRequest = PostOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PostOrderResponse PostOrderResponse;

    public PostOrderResponse1()
    {
    }

    public PostOrderResponse1(PostOrderResponse PostOrderResponse)
    {
        this.PostOrderResponse = PostOrderResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PutOrderRequest
{

    private CancelOrder orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public CancelOrder Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/OrderService")]
public partial class PutOrderResponse
{

    private Status statusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutOrderRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PutOrderRequest PutOrderRequest;

    public PutOrderRequest1()
    {
    }

    public PutOrderRequest1(PutOrderRequest PutOrderRequest)
    {
        this.PutOrderRequest = PutOrderRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutOrderResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/OrderService", Order = 0)]
    public PutOrderResponse PutOrderResponse;

    public PutOrderResponse1()
    {
    }

    public PutOrderResponse1(PutOrderResponse PutOrderResponse)
    {
        this.PutOrderResponse = PutOrderResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface OrderServiceChannel : OrderService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OrderServiceClient : System.ServiceModel.ClientBase<OrderService>, OrderService
{

    public OrderServiceClient()
    {
    }

    public OrderServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public OrderServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetOrderResponse1 OrderService.GetOrder(GetOrderRequest1 request)
    {
        return base.Channel.GetOrder(request);
    }

    public GetOrderResponse GetOrder(GetOrderRequest GetOrderRequest)
    {
        GetOrderRequest1 inValue = new GetOrderRequest1();
        inValue.GetOrderRequest = GetOrderRequest;
        GetOrderResponse1 retVal = ((OrderService)(this)).GetOrder(inValue);
        return retVal.GetOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetOrderResponse1> OrderService.GetOrderAsync(GetOrderRequest1 request)
    {
        return base.Channel.GetOrderAsync(request);
    }

    public System.Threading.Tasks.Task<GetOrderResponse1> GetOrderAsync(GetOrderRequest GetOrderRequest)
    {
        GetOrderRequest1 inValue = new GetOrderRequest1();
        inValue.GetOrderRequest = GetOrderRequest;
        return ((OrderService)(this)).GetOrderAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PostOrderResponse1 OrderService.PostOrder(PostOrderRequest1 request)
    {
        return base.Channel.PostOrder(request);
    }

    public PostOrderResponse PostOrder(PostOrderRequest PostOrderRequest)
    {
        PostOrderRequest1 inValue = new PostOrderRequest1();
        inValue.PostOrderRequest = PostOrderRequest;
        PostOrderResponse1 retVal = ((OrderService)(this)).PostOrder(inValue);
        return retVal.PostOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PostOrderResponse1> OrderService.PostOrderAsync(PostOrderRequest1 request)
    {
        return base.Channel.PostOrderAsync(request);
    }

    public System.Threading.Tasks.Task<PostOrderResponse1> PostOrderAsync(PostOrderRequest PostOrderRequest)
    {
        PostOrderRequest1 inValue = new PostOrderRequest1();
        inValue.PostOrderRequest = PostOrderRequest;
        return ((OrderService)(this)).PostOrderAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PutOrderResponse1 OrderService.PutOrder(PutOrderRequest1 request)
    {
        return base.Channel.PutOrder(request);
    }

    public PutOrderResponse PutOrder(PutOrderRequest PutOrderRequest)
    {
        PutOrderRequest1 inValue = new PutOrderRequest1();
        inValue.PutOrderRequest = PutOrderRequest;
        PutOrderResponse1 retVal = ((OrderService)(this)).PutOrder(inValue);
        return retVal.PutOrderResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PutOrderResponse1> OrderService.PutOrderAsync(PutOrderRequest1 request)
    {
        return base.Channel.PutOrderAsync(request);
    }

    public System.Threading.Tasks.Task<PutOrderResponse1> PutOrderAsync(PutOrderRequest PutOrderRequest)
    {
        PutOrderRequest1 inValue = new PutOrderRequest1();
        inValue.PutOrderRequest = PutOrderRequest;
        return ((OrderService)(this)).PutOrderAsync(inValue);
    }
}
