//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------




[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", ConfigurationName = "CustomerService")]
public interface CustomerService
{

    // CODEGEN: Se está generando un contrato de mensaje, ya que la operación PostCustomer no es RPC ni está encapsulada en un documento.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/PostCustomer", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PostCustomerResponse1 PostCustomer(PostCustomerRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/PostCustomer", ReplyAction = "*")]
    System.Threading.Tasks.Task<PostCustomerResponse1> PostCustomerAsync(PostCustomerRequest1 request);

    // CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetCustomer no es RPC ni está encapsulada en un documento.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/GetCustomer", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCustomerResponse1 GetCustomer(GetCustomerRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/GetCustomer", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetCustomerResponse1> GetCustomerAsync(GetCustomerRequest1 request);

    // CODEGEN: Se está generando un contrato de mensaje, ya que la operación PutCustomer no es RPC ni está encapsulada en un documento.
    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/PutCustomer", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    PutCustomerResponse1 PutCustomer(PutCustomerRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://xmlns.touresbalon.com/CustomerService/PutCustomer", ReplyAction = "*")]
    System.Threading.Tasks.Task<PutCustomerResponse1> PutCustomerAsync(PutCustomerRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class PostCustomerRequest
{

    private Customer customerField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Customer Customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class Customer
{

    private string idTypeField;

    private int idNumberField;

    private string firstNameField;

    private string lastNamesField;

    private string emailField;

    private string phoneNumberField;

    private string addressField;

    private string cityField;

    private string countryField;

    private string userField;

    private string passwordField;

    private CreditCard creditCardField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string FirstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string LastNames
    {
        get
        {
            return this.lastNamesField;
        }
        set
        {
            this.lastNamesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public CreditCard CreditCard
    {
        get
        {
            return this.creditCardField;
        }
        set
        {
            this.creditCardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class CreditCard
{

    private string typeField;

    private string numberField;

    private string cardNameField;

    private double expirationDateField;

    private string securityCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CardName
    {
        get
        {
            return this.cardNameField;
        }
        set
        {
            this.cardNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public double ExpirationDate
    {
        get
        {
            return this.expirationDateField;
        }
        set
        {
            this.expirationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SecurityCode
    {
        get
        {
            return this.securityCodeField;
        }
        set
        {
            this.securityCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class CreditCardGet
{

    private string typeField;

    private string numberField;

    private string cardNameField;

    private double expirationDateField;

    private string securityCodeField;

    private string statusCardField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CardName
    {
        get
        {
            return this.cardNameField;
        }
        set
        {
            this.cardNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public double ExpirationDate
    {
        get
        {
            return this.expirationDateField;
        }
        set
        {
            this.expirationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SecurityCode
    {
        get
        {
            return this.securityCodeField;
        }
        set
        {
            this.securityCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string StatusCard
    {
        get
        {
            return this.statusCardField;
        }
        set
        {
            this.statusCardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class GetCustomerResult
{

    private string idTypeField;

    private int idNumberField;

    private string firstNameField;

    private string lastNamesField;

    private string emailField;

    private string phoneNumberField;

    private string addressField;

    private string cityField;

    private string countryField;

    private string userField;

    private string passwordField;

    private string statusCustomerField;

    private CreditCardGet creditCardField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string FirstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string LastNames
    {
        get
        {
            return this.lastNamesField;
        }
        set
        {
            this.lastNamesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public string StatusCustomer
    {
        get
        {
            return this.statusCustomerField;
        }
        set
        {
            this.statusCustomerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
    public CreditCardGet CreditCard
    {
        get
        {
            return this.creditCardField;
        }
        set
        {
            this.creditCardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class GetCustomer
{

    private string idTypeField;

    private int idNumberField;

    private string firstNameField;

    private string lastNamesField;

    private string emailField;

    private string phoneNumberField;

    private string addressField;

    private string cityField;

    private string countryField;

    private string userField;

    private string statusCustomerField;

    private string passwordField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string IdType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int IdNumber
    {
        get
        {
            return this.idNumberField;
        }
        set
        {
            this.idNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string FirstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string LastNames
    {
        get
        {
            return this.lastNamesField;
        }
        set
        {
            this.lastNamesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string StatusCustomer
    {
        get
        {
            return this.statusCustomerField;
        }
        set
        {
            this.statusCustomerField = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class Status
{

    private string codeRespField;

    private string messageRespField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string CodeResp
    {
        get
        {
            return this.codeRespField;
        }
        set
        {
            this.codeRespField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string MessageResp
    {
        get
        {
            return this.messageRespField;
        }
        set
        {
            this.messageRespField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class PostCustomerResponse
{

    private Status statusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostCustomerRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public PostCustomerRequest PostCustomerRequest;

    public PostCustomerRequest1()
    {
    }

    public PostCustomerRequest1(PostCustomerRequest PostCustomerRequest)
    {
        this.PostCustomerRequest = PostCustomerRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PostCustomerResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public PostCustomerResponse PostCustomerResponse;

    public PostCustomerResponse1()
    {
    }

    public PostCustomerResponse1(PostCustomerResponse PostCustomerResponse)
    {
        this.PostCustomerResponse = PostCustomerResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class GetCustomerRequest
{

    private GetCustomer customerField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public GetCustomer Customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class GetCustomerResponse
{

    private Status statusField;

    private GetCustomerResult[] resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
    public GetCustomerResult[] result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetCustomerRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public GetCustomerRequest GetCustomerRequest;

    public GetCustomerRequest1()
    {
    }

    public GetCustomerRequest1(GetCustomerRequest GetCustomerRequest)
    {
        this.GetCustomerRequest = GetCustomerRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetCustomerResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public GetCustomerResponse GetCustomerResponse;

    public GetCustomerResponse1()
    {
    }

    public GetCustomerResponse1(GetCustomerResponse GetCustomerResponse)
    {
        this.GetCustomerResponse = GetCustomerResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class PutCustomerRequest
{

    private GetCustomer customerField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public GetCustomer Customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xmlns.touresbalon.com/CustomerService")]
public partial class PutCustomerResponse
{

    private Status statusField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutCustomerRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public PutCustomerRequest PutCustomerRequest;

    public PutCustomerRequest1()
    {
    }

    public PutCustomerRequest1(PutCustomerRequest PutCustomerRequest)
    {
        this.PutCustomerRequest = PutCustomerRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class PutCustomerResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xmlns.touresbalon.com/CustomerService", Order = 0)]
    public PutCustomerResponse PutCustomerResponse;

    public PutCustomerResponse1()
    {
    }

    public PutCustomerResponse1(PutCustomerResponse PutCustomerResponse)
    {
        this.PutCustomerResponse = PutCustomerResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CustomerServiceChannel : CustomerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerServiceClient : System.ServiceModel.ClientBase<CustomerService>, CustomerService
{

    public CustomerServiceClient()
    {
    }

    public CustomerServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PostCustomerResponse1 CustomerService.PostCustomer(PostCustomerRequest1 request)
    {
        return base.Channel.PostCustomer(request);
    }

    public PostCustomerResponse PostCustomer(PostCustomerRequest PostCustomerRequest)
    {
        PostCustomerRequest1 inValue = new PostCustomerRequest1();
        inValue.PostCustomerRequest = PostCustomerRequest;
        PostCustomerResponse1 retVal = ((CustomerService)(this)).PostCustomer(inValue);
        return retVal.PostCustomerResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PostCustomerResponse1> CustomerService.PostCustomerAsync(PostCustomerRequest1 request)
    {
        return base.Channel.PostCustomerAsync(request);
    }

    public System.Threading.Tasks.Task<PostCustomerResponse1> PostCustomerAsync(PostCustomerRequest PostCustomerRequest)
    {
        PostCustomerRequest1 inValue = new PostCustomerRequest1();
        inValue.PostCustomerRequest = PostCustomerRequest;
        return ((CustomerService)(this)).PostCustomerAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCustomerResponse1 CustomerService.GetCustomer(GetCustomerRequest1 request)
    {
        return base.Channel.GetCustomer(request);
    }

    public GetCustomerResponse GetCustomer(GetCustomerRequest GetCustomerRequest)
    {
        GetCustomerRequest1 inValue = new GetCustomerRequest1();
        inValue.GetCustomerRequest = GetCustomerRequest;
        GetCustomerResponse1 retVal = ((CustomerService)(this)).GetCustomer(inValue);
        return retVal.GetCustomerResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetCustomerResponse1> CustomerService.GetCustomerAsync(GetCustomerRequest1 request)
    {
        return base.Channel.GetCustomerAsync(request);
    }

    public System.Threading.Tasks.Task<GetCustomerResponse1> GetCustomerAsync(GetCustomerRequest GetCustomerRequest)
    {
        GetCustomerRequest1 inValue = new GetCustomerRequest1();
        inValue.GetCustomerRequest = GetCustomerRequest;
        return ((CustomerService)(this)).GetCustomerAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PutCustomerResponse1 CustomerService.PutCustomer(PutCustomerRequest1 request)
    {
        return base.Channel.PutCustomer(request);
    }

    public PutCustomerResponse PutCustomer(PutCustomerRequest PutCustomerRequest)
    {
        PutCustomerRequest1 inValue = new PutCustomerRequest1();
        inValue.PutCustomerRequest = PutCustomerRequest;
        PutCustomerResponse1 retVal = ((CustomerService)(this)).PutCustomer(inValue);
        return retVal.PutCustomerResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PutCustomerResponse1> CustomerService.PutCustomerAsync(PutCustomerRequest1 request)
    {
        return base.Channel.PutCustomerAsync(request);
    }

    public System.Threading.Tasks.Task<PutCustomerResponse1> PutCustomerAsync(PutCustomerRequest PutCustomerRequest)
    {
        PutCustomerRequest1 inValue = new PutCustomerRequest1();
        inValue.PutCustomerRequest = PutCustomerRequest;
        return ((CustomerService)(this)).PutCustomerAsync(inValue);
    }
}
