//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.touresbalon.com/LoginService", ConfigurationName="LoginService")]
public interface LoginService
{
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetLogin no es RPC ni está encapsulada en un documento.
    [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.touresbalon.com/LoginService/GetLogin", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetLoginResponse1 GetLogin(GetLoginRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.touresbalon.com/LoginService/GetLogin", ReplyAction="*")]
    System.Threading.Tasks.Task<GetLoginResponse1> GetLoginAsync(GetLoginRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.touresbalon.com/LoginService")]
public partial class GetLoginRequest
{
    
    private Login loginField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Login Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.touresbalon.com/LoginService")]
public partial class Login
{
    
    private string userField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.touresbalon.com/LoginService")]
//public partial class Status
//{
    
//    private string codeRespField;
    
//    private string messageRespField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
//    public string CodeResp
//    {
//        get
//        {
//            return this.codeRespField;
//        }
//        set
//        {
//            this.codeRespField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
//    public string MessageResp
//    {
//        get
//        {
//            return this.messageRespField;
//        }
//        set
//        {
//            this.messageRespField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.touresbalon.com/LoginService")]
public partial class GetLoginResponse
{
    
    private Status statusField;
    
    private GetCustomerResult[] resultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Status status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable=false)]
    public GetCustomerResult[] result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLoginRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.touresbalon.com/LoginService", Order=0)]
    public GetLoginRequest GetLoginRequest;
    
    public GetLoginRequest1()
    {
    }
    
    public GetLoginRequest1(GetLoginRequest GetLoginRequest)
    {
        this.GetLoginRequest = GetLoginRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLoginResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.touresbalon.com/LoginService", Order=0)]
    public GetLoginResponse GetLoginResponse;
    
    public GetLoginResponse1()
    {
    }
    
    public GetLoginResponse1(GetLoginResponse GetLoginResponse)
    {
        this.GetLoginResponse = GetLoginResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface LoginServiceChannel : LoginService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginServiceClient : System.ServiceModel.ClientBase<LoginService>, LoginService
{
    
    public LoginServiceClient()
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetLoginResponse1 LoginService.GetLogin(GetLoginRequest1 request)
    {
        return base.Channel.GetLogin(request);
    }
    
    public GetLoginResponse GetLogin(GetLoginRequest GetLoginRequest)
    {
        GetLoginRequest1 inValue = new GetLoginRequest1();
        inValue.GetLoginRequest = GetLoginRequest;
        GetLoginResponse1 retVal = ((LoginService)(this)).GetLogin(inValue);
        return retVal.GetLoginResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetLoginResponse1> LoginService.GetLoginAsync(GetLoginRequest1 request)
    {
        return base.Channel.GetLoginAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetLoginResponse1> GetLoginAsync(GetLoginRequest GetLoginRequest)
    {
        GetLoginRequest1 inValue = new GetLoginRequest1();
        inValue.GetLoginRequest = GetLoginRequest;
        return ((LoginService)(this)).GetLoginAsync(inValue);
    }
}
